Repository epigram5-9/epigram, pull requests merged in 2024-07, with the labels that each got.

#3 doc: README.md & userQueryHooks.ts 수정
  README.md
  src/hooks/userQueryHooks.ts
Labels: Type: Doc :memo:

#5 .nvmrc 버전 수정
  .nvmrc
Labels: Priority: Low 🐢

#6 폰트 및 공용컬러 추가
  public/epigram-icon.png
  src/pages/_document.tsx
  src/pages/index.tsx
  src/styles/Home.module.css
  src/styles/globals.css
  tailwind.config.js
Labels: Priority: Low 🐢

#7 :lipstick: shadcn ui setup
  .eslintrc.js
  components.json
  package-lock.json
  package.json
  src/components/ui/alert-dialog.tsx
  src/components/ui/avatar.tsx
  src/components/ui/badge.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/radio-group.tsx
  src/components/ui/switch.tsx
  src/components/ui/textarea.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/components/ui/use-toast.ts
  src/lib/utils.ts
  tailwind.config.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#11 [Merge] epic/FE-29브랜치 최신화
  .eslintrc.js
  .nvmrc
  components.json
  package-lock.json
  package.json
  public/epigram-icon.png
  src/components/ui/alert-dialog.tsx
  src/components/ui/avatar.tsx
  src/components/ui/badge.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/radio-group.tsx
  src/components/ui/switch.tsx
  src/components/ui/textarea.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/components/ui/use-toast.ts
  src/lib/utils.ts
  src/pages/_document.tsx
  src/pages/index.tsx
  src/styles/Home.module.css
  src/styles/globals.css
  tailwind.config.js
  tailwind.config.ts
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#12 FE-31 상세페이지 UI 제작
  public/arrow-left.svg
  public/likeIcon.svg
  public/logo.svg
  public/placeLink.svg
  public/profile.svg
  public/share.svg
  src/pageLayout/Epigram/EpigramComment.tsx
  src/pageLayout/Epigram/EpigramFigure.tsx
  src/pageLayout/Epigram/EpigramLayout.tsx
  src/pages/epigram/[id].tsx
Labels: Priority: Low 🐢

#9 FE-48 ✨ 공용 컴포넌트 EmotionSelector 구현
  public/favicon.ico
  public/icon/BW/AngryFaceBWIcon.svg
  public/icon/BW/HeartFaceBWIcon.svg
  public/icon/BW/SadFaceBWIcon.svg
  public/icon/BW/SmileFaceBWIcon.svg
  public/icon/BW/ThinkFaceBWIcon.svg
  public/icon/Color/AngryFaceColorIcon.svg
  public/icon/Color/HeartFaceColorIcon.svg
  public/icon/Color/SadFaceColorIcon.svg
  public/icon/Color/SmileFaceColorIcon.svg
  public/icon/Color/ThinkFaceColorIcon.svg
  public/next.svg
  public/vercel.svg
  src/components/Emotion/card/EmotionIconCard.tsx
  src/components/Emotion/card/EmotionSelector.tsx
  src/components/Emotion/card/InteractiveEmotionIconCard.tsx
  src/hooks/useMediaQuery.ts
  src/types/EmotionTypes.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#14 FE-28 ✨ 마이페이지 ui 레이아웃 작업
  .eslintrc.js
  .nvmrc
  public/epigram-icon.png
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/pageLayout/MypageLayout/index.ts
  src/pages/_document.tsx
  src/pages/index.tsx
  src/pages/mypage/index.tsx
  src/styles/Home.module.css
  src/styles/globals.css
  tailwind.config.js
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#13 FE-30 :lipstick: 로그인 페이지 ui 및 반응형 디자인 생성
  public/lg.svg
  public/logo-google.svg
  public/logo-kakao.svg
  public/logo-naver.svg
  src/pageLayout/AuthLayout/AuthLayout.tsx
  src/pages/auth/SignIn.tsx
Labels: Priority: Medium :bookmark:

#15 FE-27 :twisted_rightwards_arrows: epic/FE-27 브랜치 최신화
  .eslintrc.js
  components.json
  package-lock.json
  package.json
  src/components/ui/alert-dialog.tsx
  src/components/ui/avatar.tsx
  src/components/ui/badge.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/radio-group.tsx
  src/components/ui/switch.tsx
  src/components/ui/textarea.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/components/ui/use-toast.ts
  src/lib/utils.ts
  tailwind.config.ts
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#16 FE-59 ✨ 공용 컴포넌트 에피그램 카드 구현
  src/components/Card/EpigramCard.tsx
  src/pages/index.tsx
  tailwind.config.js
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#10 💄FE-33 검색 페이지 UI
  .eslintrc.js
  .nvmrc
  .vscode/settings.json
  components.json
  package-lock.json
  package.json
  public/epigram-icon.png
  public/md.svg
  src/components/index.tsx
  src/components/search/RecentSearches.tsx
  src/components/search/SearchBar.tsx
  src/components/search/SearchResults.tsx
  src/components/ui/alert-dialog.tsx
  src/components/ui/avatar.tsx
  src/components/ui/badge.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/radio-group.tsx
  src/components/ui/switch.tsx
  src/components/ui/textarea.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/components/ui/use-toast.ts
  src/lib/utils.ts
  src/pageLayout/SearchLayout/SearchLayout.tsx
  src/pageLayout/index.ts
  src/pages/_document.tsx
  src/pages/index.tsx
  src/pages/search/index.tsx
  src/styles/Home.module.css
  src/styles/globals.css
  tailwind.config.js
  tailwind.config.ts
  tsconfig.json
Labels: Priority: Medium :bookmark:

#17 FE-58 ✨ 공용 컴포넌트 댓글 카드 구현
  public/ProfileTestImage.jpg
  src/components/Card/CommentCard.tsx
  src/styles/CommentCardStyles.ts
  src/types/CommentCardTypes.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#19 FE-50 ✨공용컴포넌트 헤더 구현
  package-lock.json
  package.json
  public/icon/arrow-left-icon.svg
  public/icon/profile-icon.svg
  public/icon/search-icon.svg
  public/icon/share-icon.svg
  src/components/Header/Header.tsx
  src/types/Header.ts
  tailwind.config.js
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#20 FE-60 :sparkles: 로그인 페이지 유효성 검사
  src/pages/auth/SignIn.tsx
  src/schema/auth.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#21 FE-46 ✨ 공용 컴포넌트 구현
  package-lock.json
  package.json
  public/ProfileTestImage.jpg
  public/favicon.ico
  public/icon/BW/AngryFaceBWIcon.svg
  public/icon/BW/HeartFaceBWIcon.svg
  public/icon/BW/SadFaceBWIcon.svg
  public/icon/BW/SmileFaceBWIcon.svg
  public/icon/BW/ThinkFaceBWIcon.svg
  public/icon/Color/AngryFaceColorIcon.svg
  public/icon/Color/HeartFaceColorIcon.svg
  public/icon/Color/SadFaceColorIcon.svg
  public/icon/Color/SmileFaceColorIcon.svg
  public/icon/Color/ThinkFaceColorIcon.svg
  public/icon/arrow-left-icon.svg
  public/icon/profile-icon.svg
  public/icon/search-icon.svg
  public/icon/share-icon.svg
  public/next.svg
  public/vercel.svg
  src/components/Card/CommentCard.tsx
  src/components/Card/EpigramCard.tsx
  src/components/Emotion/card/EmotionIconCard.tsx
  src/components/Emotion/card/EmotionSelector.tsx
  src/components/Emotion/card/InteractiveEmotionIconCard.tsx
  src/components/Header/Header.tsx
  src/hooks/useMediaQuery.ts
  src/pages/index.tsx
  src/styles/CommentCardStyles.ts
  src/types/CommentCardTypes.ts
  src/types/EmotionTypes.ts
  src/types/Header.ts
  tailwind.config.js
Labels: Priority: High 🔥, Type: Epic :rocket:

#18 FE-43 ✨ 상세페이지 에피그램 조회
  src/apis/epigram.ts
  src/apis/queries.ts
  src/apis/user.ts
  src/hooks/epigramQueryHook.ts
  src/hooks/userQueryHooks.ts
  src/pageLayout/Epigram/EpigramComment.tsx
  src/pageLayout/Epigram/EpigramFigure.tsx
  src/pageLayout/Epigram/EpigramLayout.tsx
  src/pages/epigram/[id].tsx
  src/schema/epigram.ts
  src/schema/user.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#22 FE-43✨ 사용자 ID에 따른 미트볼아이콘 표시
  public/meatballIcon.svg
  src/apis/epigram.ts
  src/apis/user.ts
  src/components/epigram/MoreOptionMenu.tsx
  src/lib/constants.ts
  src/pageLayout/Epigram/EpigramFigure.tsx
  src/pages/epigram/[id].tsx
  src/types/epigram.types.ts
Labels: Priority: Low 🐢, Type: Feature :sparkles:

#24 FE-61 🔨 공용 컴포넌트 수정
  .eslintrc.js
  src/components/Card/CommentCard.tsx
  src/components/Card/EpigramCard.tsx
  src/components/Emotion/EmotionCard.tsx
  src/components/Emotion/EmotionSelector.tsx
  src/components/Emotion/card/InteractiveEmotionIconCard.tsx
  src/types/CommentCardTypes.ts
Labels: Priority: Medium :bookmark:, Type: Bug :bug:

#27 FE-62 ✨fix: 주석 수정 및 타입 수정
  src/components/Header/Header.tsx
  src/types/Header.ts
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#26 🔀 epic/FE-54--detail-page 브랜치 최신화
  package-lock.json
  package.json
  public/ProfileTestImage.jpg
  public/favicon.ico
  public/icon/BW/AngryFaceBWIcon.svg
  public/icon/BW/HeartFaceBWIcon.svg
  public/icon/BW/SadFaceBWIcon.svg
  public/icon/BW/SmileFaceBWIcon.svg
  public/icon/BW/ThinkFaceBWIcon.svg
  public/icon/Color/AngryFaceColorIcon.svg
  public/icon/Color/HeartFaceColorIcon.svg
  public/icon/Color/SadFaceColorIcon.svg
  public/icon/Color/SmileFaceColorIcon.svg
  public/icon/Color/ThinkFaceColorIcon.svg
  public/icon/arrow-left-icon.svg
  public/icon/profile-icon.svg
  public/icon/search-icon.svg
  public/icon/share-icon.svg
  public/next.svg
  public/vercel.svg
  src/components/Card/CommentCard.tsx
  src/components/Card/EpigramCard.tsx
  src/components/Emotion/card/EmotionIconCard.tsx
  src/components/Emotion/card/EmotionSelector.tsx
  src/components/Emotion/card/InteractiveEmotionIconCard.tsx
  src/components/Header/Header.tsx
  src/hooks/useMediaQuery.ts
  src/pages/index.tsx
  src/styles/CommentCardStyles.ts
  src/types/CommentCardTypes.ts
  src/types/EmotionTypes.ts
  src/types/Header.ts
  tailwind.config.js
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#23 :twisted_rightwards_arrows: epic/FE-29 브랜치 최신화
  package-lock.json
  package.json
  public/ProfileTestImage.jpg
  public/favicon.ico
  public/icon/BW/AngryFaceBWIcon.svg
  public/icon/BW/HeartFaceBWIcon.svg
  public/icon/BW/SadFaceBWIcon.svg
  public/icon/BW/SmileFaceBWIcon.svg
  public/icon/BW/ThinkFaceBWIcon.svg
  public/icon/Color/AngryFaceColorIcon.svg
  public/icon/Color/HeartFaceColorIcon.svg
  public/icon/Color/SadFaceColorIcon.svg
  public/icon/Color/SmileFaceColorIcon.svg
  public/icon/Color/ThinkFaceColorIcon.svg
  public/icon/arrow-left-icon.svg
  public/icon/profile-icon.svg
  public/icon/search-icon.svg
  public/icon/share-icon.svg
  public/next.svg
  public/vercel.svg
  src/components/Card/CommentCard.tsx
  src/components/Card/EpigramCard.tsx
  src/components/Emotion/card/EmotionIconCard.tsx
  src/components/Emotion/card/EmotionSelector.tsx
  src/components/Emotion/card/InteractiveEmotionIconCard.tsx
  src/components/Header/Header.tsx
  src/hooks/useMediaQuery.ts
  src/pages/index.tsx
  src/styles/CommentCardStyles.ts
  src/types/CommentCardTypes.ts
  src/types/EmotionTypes.ts
  src/types/Header.ts
  tailwind.config.js
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#29 FE-21 ✨ 소개 페이지 ui 구현
  public/AboutPage/ArrowDownIcon.svg
  public/AboutPage/Desktop/AboutEpigram1.png
  public/AboutPage/Desktop/AboutEpigram2.png
  public/AboutPage/Desktop/AboutEpigram3.png
  public/AboutPage/Desktop/AboutEpigram4.png
  public/AboutPage/Logo/LogoLG.svg
  public/AboutPage/Logo/LogoSM.svg
  public/AboutPage/Logo/LogoXL.svg
  public/AboutPage/Mobile/AboutEpigram1.png
  public/AboutPage/Mobile/AboutEpigram2.png
  public/AboutPage/Mobile/AboutEpigram3.png
  public/AboutPage/Mobile/AboutEpigram4.png
  public/AboutPage/Tablet/AboutEpigram1.png
  public/AboutPage/Tablet/AboutEpigram2.png
  public/AboutPage/Tablet/AboutEpigram3.png
  public/AboutPage/Tablet/AboutEpigram4.png
  src/pages/index.tsx
  tailwind.config.js
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#30 FE-24 :sparkles: 소개 페이지 이동 구현
  src/pages/index.tsx
Labels: Priority: Low 🐢, Type: Feature :sparkles:

#28 FE-34 :sparkles: 마이페이지 프로필 수정 기능
  next.config.mjs
  package-lock.json
  package.json
  public/ProfileTestImage.jpg
  public/favicon.ico
  public/icon/BW/AngryFaceBWIcon.svg
  public/icon/BW/HeartFaceBWIcon.svg
  public/icon/BW/SadFaceBWIcon.svg
  public/icon/BW/SmileFaceBWIcon.svg
  public/icon/BW/ThinkFaceBWIcon.svg
  public/icon/Color/AngryFaceColorIcon.svg
  public/icon/Color/HeartFaceColorIcon.svg
  public/icon/Color/SadFaceColorIcon.svg
  public/icon/Color/SmileFaceColorIcon.svg
  public/icon/Color/ThinkFaceColorIcon.svg
  public/icon/arrow-left-icon.svg
  public/icon/profile-icon.svg
  public/icon/search-icon.svg
  public/icon/share-icon.svg
  public/icon/x-icon_md.svg
  public/next.svg
  public/user-profile_sample/user-profile_sample1.jpg
  public/vercel.svg
  src/apis/index.ts
  src/apis/user.ts
  src/components/Card/CommentCard.tsx
  src/components/Card/EpigramCard.tsx
  src/components/Emotion/card/EmotionIconCard.tsx
  src/components/Emotion/card/EmotionSelector.tsx
  src/components/Emotion/card/InteractiveEmotionIconCard.tsx
  src/components/Header/Header.tsx
  src/hooks/useMediaQuery.ts
  src/hooks/userQueryHooks.ts
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/pageLayout/MypageLayout/index.ts
  src/pages/index.tsx
  src/pages/mypage/index.tsx
  src/schema/user.ts
  src/styles/CommentCardStyles.ts
  src/styles/globals.css
  src/types/CommentCardTypes.ts
  src/types/EmotionTypes.ts
  src/types/Header.ts
  src/types/user.ts
  src/user/ui-profile/Profile.tsx
  src/user/ui-profile/ProfileEdit.tsx
  src/user/util/constants.ts
  src/user/util/fileNameChange.ts
  tailwind.config.js
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#31 🔀 epic/FE-13--main-page 브랜치 최신화
  package-lock.json
  package.json
  public/ProfileTestImage.jpg
  public/favicon.ico
  public/icon/BW/AngryFaceBWIcon.svg
  public/icon/BW/HeartFaceBWIcon.svg
  public/icon/BW/SadFaceBWIcon.svg
  public/icon/BW/SmileFaceBWIcon.svg
  public/icon/BW/ThinkFaceBWIcon.svg
  public/icon/Color/AngryFaceColorIcon.svg
  public/icon/Color/HeartFaceColorIcon.svg
  public/icon/Color/SadFaceColorIcon.svg
  public/icon/Color/SmileFaceColorIcon.svg
  public/icon/Color/ThinkFaceColorIcon.svg
  public/icon/arrow-left-icon.svg
  public/icon/profile-icon.svg
  public/icon/search-icon.svg
  public/icon/share-icon.svg
  public/next.svg
  public/vercel.svg
  src/components/Card/CommentCard.tsx
  src/components/Card/EpigramCard.tsx
  src/components/Emotion/card/EmotionIconCard.tsx
  src/components/Emotion/card/EmotionSelector.tsx
  src/components/Emotion/card/InteractiveEmotionIconCard.tsx
  src/components/Header/Header.tsx
  src/hooks/useMediaQuery.ts
  src/pages/index.tsx
  src/styles/CommentCardStyles.ts
  src/types/CommentCardTypes.ts
  src/types/EmotionTypes.ts
  src/types/Header.ts
  tailwind.config.js
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#34 FE-52 ✨에피그램 목록조회 API
  src/apis/.http
  src/apis/getEpigrams.ts
  src/schema/epigrams.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#38 ✨ 상세페이지 댓글 조회 api연동
  package-lock.json
  package.json
  src/apis/epigram.ts
  src/apis/epigramComment.ts
  src/apis/queries.ts
  src/components/epigram/Comment/CommentItem.tsx
  src/components/epigram/Comment/CommentList.tsx
  src/components/epigram/Comment/NoComment.tsx
  src/hooks/useEpigramCommentsQueryHook.ts
  src/hooks/useEpigramQueryHook.ts
  src/lib/constants.ts
  src/lib/dateUtils.ts
  src/pageLayout/Epigram/EpigramComment.tsx
  src/pages/epigram/[id].tsx
  src/schema/comment.ts
  src/types/epigram.types.ts
Labels: Priority: High 🔥, Type: Feature :sparkles:

#36 FE-63 :sparkles: 로그인 api 연동
  src/apis/auth.ts
  src/apis/index.ts
  src/hooks/userQueryHooks.ts
  src/pages/auth/SignIn.tsx
  src/schema/auth.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#37 FE-67 :lipstick: 회원가입 페이지 ui 및 반응형 디자인 제작
  public/lg.svg
  public/logo-google.svg
  public/logo-kakao.svg
  public/logo-naver.svg
  src/pageLayout/AuthLayout/AuthLayout.tsx
  src/pages/auth/SignUp.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#42 FE-27 :twisted_rightwards_arrows: epic 브랜치 최신화
  package-lock.json
  src/pages/index.tsx
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#40 FE-68 :sparkles: 회원가입 페이지 유효성 검사
  src/pages/auth/SignUp.tsx
  src/schema/auth.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#44 💄 글작성 페이지 UI추가
  src/pageLayout/Epigram/AddEpigram.tsx
  src/pages/epigram/add.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#32 FE-46 🔨 공용 컴포넌트 멘토링 수정사항 반영
  .eslintrc.js
  src/components/Card/CommentCard.tsx
  src/components/Card/EpigramCard.tsx
  src/components/Emotion/EmotionCard.tsx
  src/components/Emotion/EmotionSelector.tsx
  src/components/Emotion/card/InteractiveEmotionIconCard.tsx
  src/components/Header/Header.tsx
  src/types/CommentCardTypes.ts
  src/types/Header.ts
Labels: Priority: High 🔥, Type: Bug :bug:

#48 FE-66 :wrench: 회원가입 페이지 ui 수정
  src/pageLayout/AuthLayout/AuthLayout.tsx
  src/pages/auth/SignUp.tsx
  src/schema/auth.ts
Labels: Priority: Medium :bookmark:, Type: Improve UX :arrow_up:

#49 FE-51 🔀 epic 브랜치 최신화
  .eslintrc.js
  package-lock.json
  package.json
  public/ProfileTestImage.jpg
  public/favicon.ico
  public/icon/BW/AngryFaceBWIcon.svg
  public/icon/BW/HeartFaceBWIcon.svg
  public/icon/BW/SadFaceBWIcon.svg
  public/icon/BW/SmileFaceBWIcon.svg
  public/icon/BW/ThinkFaceBWIcon.svg
  public/icon/Color/AngryFaceColorIcon.svg
  public/icon/Color/HeartFaceColorIcon.svg
  public/icon/Color/SadFaceColorIcon.svg
  public/icon/Color/SmileFaceColorIcon.svg
  public/icon/Color/ThinkFaceColorIcon.svg
  public/icon/arrow-left-icon.svg
  public/icon/profile-icon.svg
  public/icon/search-icon.svg
  public/icon/share-icon.svg
  public/next.svg
  public/vercel.svg
  src/components/Card/CommentCard.tsx
  src/components/Card/EpigramCard.tsx
  src/components/Emotion/EmotionCard.tsx
  src/components/Emotion/EmotionSelector.tsx
  src/components/Header/Header.tsx
  src/hooks/useMediaQuery.ts
  src/pages/index.tsx
  src/styles/CommentCardStyles.ts
  src/types/EmotionTypes.ts
  tailwind.config.js
Labels: Priority: Low 🐢, Type: Merge :truck:

#51 FE-65 ✨최근 검색어 기능
  package-lock.json
  package.json
  src/components/search/RecentSearches.tsx
  src/components/search/SearchBar.tsx
  src/pageLayout/SearchLayout/SearchLayout.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#50 FE-29 :twisted_rightwards_arrows: epic브랜치 최신화
  .eslintrc.js
  src/components/Card/CommentCard.tsx
  src/components/Card/EpigramCard.tsx
  src/components/Emotion/EmotionCard.tsx
  src/components/Emotion/EmotionSelector.tsx
  src/components/Emotion/card/InteractiveEmotionIconCard.tsx
  src/components/Header/Header.tsx
  src/types/CommentCardTypes.ts
  src/types/Header.ts
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#54 FE-29 :recycle: 코드 리뷰에 대한 리팩토링
  src/apis/auth.ts
  src/apis/index.ts
  src/hooks/useSignInMutation.ts
  src/hooks/userQueryHooks.ts
  src/pageLayout/AuthLayout/AuthLayout.tsx
  src/pages/_app.tsx
  src/pages/auth/SignIn.tsx
Labels: Priority: High 🔥, Type: Refactor :recycle:

#53 FE-34 :sparkles: 마이페이지 프로필 수정 기능
  next.config.mjs
  package-lock.json
  package.json
  src/apis/index.ts
  src/apis/user.ts
  src/components/ui/dialog.tsx
  src/hooks/userQueryHooks.ts
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/pages/_app.tsx
  src/pages/mypage/index.tsx
  src/schema/user.ts
  src/types/user.ts
  src/user/ui-profile/Profile.tsx
  src/user/ui-profile/ProfileEdit.tsx
  src/user/utill/constants.ts
  src/user/utill/fileNameChange.ts
  tailwind.config.js
Labels: Priority: High 🔥, Type: Feature :sparkles:

#55 FE-66 :twisted_rightwards_arrows: epic브랜치 최신화
  .eslintrc.js
  src/components/Card/CommentCard.tsx
  src/components/Card/EpigramCard.tsx
  src/components/Emotion/EmotionCard.tsx
  src/components/Emotion/EmotionSelector.tsx
  src/components/Emotion/card/InteractiveEmotionIconCard.tsx
  src/components/Header/Header.tsx
  src/types/CommentCardTypes.ts
  src/types/Header.ts
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#52 FE-72 ✨ 에피그램 등록 api연동
  src/apis/add.ts
  src/apis/index.ts
  src/hooks/epigramQueryHook.ts
  src/pageLayout/Epigram/AddEpigram.tsx
  src/pages/epigram/[id].tsx
  src/schema/addEpigram.ts
Labels: Priority: High 🔥, Type: Feature :sparkles:

#58 FE-36 :sparkles: 마이페이지 캘린더 출력 함수
  package-lock.json
  package.json
  public/icon/arrow-bottom-icon.svg
  public/icon/arrow-right-icon.svg
  src/hooks/useCalendar.ts
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/user/ui-profile/Calendar.tsx
  src/user/utill/constants.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#60 FE-53 ✨ 오늘의 감정 저장, 조회 기능 구현
  src/apis/getEmotion.ts
  src/apis/postEmotion.ts
  src/components/Emotion/EmotionCard.tsx
  src/components/Emotion/EmotionSaveToast.tsx
  src/components/Emotion/EmotionSelector.tsx
  src/hooks/useGetEmotion.ts
  src/hooks/usePostEmotion.ts
  src/schema/emotion.ts
  src/types/emotion.ts
  src/utils/emotionMap.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#62 FE-18 ✨ 최근 댓글 조회 기능 구현
  src/apis/getRecentComments.ts
  src/components/Card/CommentCard.tsx
  src/components/main/RecentComment.tsx
  src/hooks/useGetRecentComments.ts
  src/schema/recentcomment.ts
  src/types/CommentCardTypes.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#64 FE-17 ✨ 최근 에피그램 조회 기능 구현
  src/apis/getRecentEpigrams.ts
  src/components/main/RecentEpigram.tsx
  src/hooks/useGetRecentEpigrams.ts
  src/schema/recentEpigram.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#65 FE-36 :sparkles: 마이페이지 감정달력
  src/apis/emotion.ts
  src/apis/index.ts
  src/apis/queries.ts
  src/hooks/useGetEmotion.ts
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/schema/emotion.ts
  src/types/emotion.ts
  src/user/ui-profile/Calendar.tsx
  src/user/ui-profile/CalendarHeader.tsx
  src/user/utill/constants.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#66 FE-73✨ 유효성검사 추가
  src/apis/index.ts
  src/hooks/useTagManagementHook.ts
  src/pageLayout/Epigram/AddEpigram.tsx
  src/schema/addEpigram.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#69 FE-69 :recycle: mutation hook 에러처리 변경
  src/hooks/useRegisterMutation.ts
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#68 FE-18 :sparkles: 최근 댓글 더보기 기능 구현
  src/apis/getRecentComments.ts
  src/components/main/RecentComment.tsx
  src/hooks/useGetRecentComments.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#59 FE-66 :sparkles: 회원가입 페이지 api
  src/apis/auth.ts
  src/hooks/useRegisterMutation.ts
  src/pages/_app.tsx
  src/pages/auth/SignUp.tsx
  src/schema/auth.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#70 FE-71🔀epic 브랜치 최신화
  .eslintrc.js
  src/components/Card/CommentCard.tsx
  src/components/Card/EpigramCard.tsx
  src/components/Emotion/EmotionCard.tsx
  src/components/Emotion/EmotionSelector.tsx
  src/components/Emotion/card/InteractiveEmotionIconCard.tsx
  src/components/Header/Header.tsx
  src/types/CommentCardTypes.ts
  src/types/Header.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#39 FE-29 :twisted_rightwards_arrows: 로그인 페이지 머지 요청
  public/lg.svg
  public/logo-google.svg
  public/logo-kakao.svg
  public/logo-naver.svg
  src/apis/auth.ts
  src/apis/index.ts
  src/hooks/useSignInMutation.ts
  src/pages/_app.tsx
  src/pages/auth/SignIn.tsx
  src/schema/auth.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#74 FE-66 :twisted_rightwards_arrows: epic브랜치 최신화 및 충돌 해결
  src/apis/auth.ts
  src/apis/index.ts
  src/hooks/useRegisterMutation.ts
  src/hooks/useSignInMutation.ts
  src/pages/auth/SignIn.tsx
  src/schema/auth.ts
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#75 FE-71 🔀 epic브랜치 최신화
  public/lg.svg
  public/logo-google.svg
  public/logo-kakao.svg
  public/logo-naver.svg
  src/apis/auth.ts
  src/apis/index.ts
  src/hooks/useSignInMutation.ts
  src/pages/_app.tsx
  src/pages/auth/SignIn.tsx
  src/schema/auth.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#76 FE-71♻️ epic브랜치 코드리뷰 반영
  src/apis/index.ts
  src/hooks/useTagManagementHook.ts
  src/pageLayout/Epigram/AddEpigram.tsx
  src/pages/addEpigram.tsx
  src/pages/epigram/[id].tsx
Labels: Priority: High 🔥, Type: Refactor :recycle:

#73 FE-74 ✨검색 결과 기능
  package-lock.json
  package.json
  src/components/search/SearchBar.tsx
  src/components/search/SearchResults.tsx
  src/components/search/test.ts
  src/pageLayout/SearchLayout/SearchLayout.tsx
  src/pages/epigram/[id]/index.tsx
  src/schema/epigrams.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#77 FE-32 🔀 epic브랜치 최신화
  .eslintrc.js
  package-lock.json
  package.json
  public/ProfileTestImage.jpg
  public/favicon.ico
  public/icon/BW/AngryFaceBWIcon.svg
  public/icon/BW/HeartFaceBWIcon.svg
  public/icon/BW/SadFaceBWIcon.svg
  public/icon/BW/SmileFaceBWIcon.svg
  public/icon/BW/ThinkFaceBWIcon.svg
  public/icon/Color/AngryFaceColorIcon.svg
  public/icon/Color/HeartFaceColorIcon.svg
  public/icon/Color/SadFaceColorIcon.svg
  public/icon/Color/SmileFaceColorIcon.svg
  public/icon/Color/ThinkFaceColorIcon.svg
  public/icon/arrow-left-icon.svg
  public/icon/profile-icon.svg
  public/icon/search-icon.svg
  public/icon/share-icon.svg
  public/lg.svg
  public/logo-google.svg
  public/logo-kakao.svg
  public/logo-naver.svg
  public/next.svg
  public/vercel.svg
  src/apis/auth.ts
  src/apis/index.ts
  src/components/Card/CommentCard.tsx
  src/components/Card/EpigramCard.tsx
  src/components/Emotion/EmotionCard.tsx
  src/components/Emotion/EmotionSelector.tsx
  src/components/Header/Header.tsx
  src/hooks/useMediaQuery.ts
  src/hooks/useSignInMutation.ts
  src/pages/_app.tsx
  src/pages/auth/SignIn.tsx
  src/pages/index.tsx
  src/schema/auth.ts
  src/styles/CommentCardStyles.ts
  src/types/EmotionTypes.ts
  tailwind.config.js
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#79 FE-71♻️ 코드리뷰 반영
  src/pageLayout/Epigram/AddEpigram.tsx
Labels: Priority: High 🔥, Type: Refactor :recycle:

#78 FE-76✨ 댓글 작성 api 연동
  public/icon/cancelIcon.svg
  src/apis/epigram.ts
  src/apis/epigramComment.ts
  src/apis/index.ts
  src/apis/queries.ts
  src/components/epigram/Comment/CommentTextarea.tsx
  src/components/ui/switch.tsx
  src/hooks/useEpigramCommentsQueryHook.ts
  src/hooks/useEpigramQueryHook.ts
  src/hooks/usePostCommentHook.ts
  src/pageLayout/Epigram/EpigramComment.tsx
  src/pages/epigram/[id].tsx
  src/schema/comment.ts
  src/schema/epigram.ts
  src/types/epigram.types.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#71 FE-71 🔀 에피그램 작성 페이지
  src/apis/add.ts
  src/apis/index.ts
  src/hooks/epigramQueryHook.ts
  src/hooks/useTagManagementHook.ts
  src/pageLayout/Epigram/AddEpigram.tsx
  src/pages/addEpigram.tsx
  src/schema/addEpigram.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#81 FE-27 :twisted_rightwards_arrows: 에픽 브랜치 최신화
  public/lg.svg
  public/logo-google.svg
  public/logo-kakao.svg
  public/logo-naver.svg
  src/apis/add.ts
  src/apis/auth.ts
  src/apis/index.ts
  src/hooks/epigramQueryHook.ts
  src/hooks/useSignInMutation.ts
  src/hooks/useTagManagementHook.ts
  src/pageLayout/Epigram/AddEpigram.tsx
  src/pages/addEpigram.tsx
  src/pages/auth/SignIn.tsx
  src/schema/addEpigram.ts
  src/schema/auth.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#87 FE-66 :twisted_rightwards_arrows: epic 브랜치 최신화
  src/apis/add.ts
  src/apis/index.ts
  src/hooks/epigramQueryHook.ts
  src/hooks/useTagManagementHook.ts
  src/pageLayout/Epigram/AddEpigram.tsx
  src/pages/addEpigram.tsx
  src/schema/addEpigram.ts
Labels: Priority: Low 🐢, Type: Merge :truck:

#84 FE-56 :sparkles: 댓글 수정 API
  public/lg.svg
  public/logo-google.svg
  public/logo-kakao.svg
  public/logo-naver.svg
  src/apis/add.ts
  src/apis/auth.ts
  src/apis/epigramComment.ts
  src/apis/index.ts
  src/apis/user.ts
  src/hooks/epigramQueryHook.ts
  src/hooks/usePatchCommentHook.ts
  src/hooks/useSignInMutation.ts
  src/hooks/useTagManagementHook.ts
  src/hooks/userQueryHooks.ts
  src/pageLayout/Epigram/AddEpigram.tsx
  src/pages/_app.tsx
  src/pages/addEpigram.tsx
  src/pages/auth/SignIn.tsx
  src/schema/addEpigram.ts
  src/schema/auth.ts
  src/schema/comment.ts
  src/schema/epigram.ts
  src/schema/user.ts
  src/types/epigram.types.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#80 FE-45✨ 에피그램 삭제 api 연동
  src/apis/epigram.ts
  src/apis/index.ts
  src/apis/queries.ts
  src/components/epigram/DeleteAlertModal.tsx
  src/components/epigram/MoreOptionMenu.tsx
  src/hooks/useDeleteEpigramHook.ts
  src/pageLayout/Epigram/EpigramFigure.tsx
  src/pages/_app.tsx
  src/types/epigram.types.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#90 FE-54🔀 epic브랜치 최신화
  .eslintrc.js
  public/lg.svg
  public/logo-google.svg
  public/logo-kakao.svg
  public/logo-naver.svg
  src/apis/add.ts
  src/apis/auth.ts
  src/apis/index.ts
  src/components/Card/CommentCard.tsx
  src/components/Card/EpigramCard.tsx
  src/components/Emotion/EmotionCard.tsx
  src/components/Emotion/EmotionSelector.tsx
  src/components/Emotion/card/InteractiveEmotionIconCard.tsx
  src/components/Header/Header.tsx
  src/components/epigram/Comment/CommentItem.tsx
  src/hooks/epigramQueryHook.ts
  src/hooks/useSignInMutation.ts
  src/hooks/useTagManagementHook.ts
  src/pageLayout/Epigram/AddEpigram.tsx
  src/pages/addEpigram.tsx
  src/pages/auth/SignIn.tsx
  src/schema/addEpigram.ts
  src/schema/auth.ts
  src/types/CommentCardTypes.ts
  src/types/Header.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#88 FE-57 :sparkles: 댓글 삭제 API
  src/apis/epigramComment.ts
  src/hooks/useDeleteCommentHook.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#89 FE-37 :sparkles: 마이페이지 감정차트
  src/hooks/useCalendar.ts
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/types/emotion.ts
  src/user/ui-profile/Calendar.tsx
  src/user/ui-profile/CalendarHeader.tsx
  src/user/ui-profile/Chart.tsx
  src/user/ui-profile/EmotionMonthlyLogs.tsx
  src/user/utill/constants.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#95 FE-66 :recycle: 에러처리 로직 수정
  src/hooks/useRegisterMutation.ts
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#94 FE-29 :twisted_rightwards_arrows: epic 브랜치 최신화
  src/apis/add.ts
  src/apis/index.ts
  src/hooks/epigramQueryHook.ts
  src/hooks/useTagManagementHook.ts
  src/pageLayout/Epigram/AddEpigram.tsx
  src/pages/addEpigram.tsx
  src/schema/addEpigram.ts
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#83 FE-70 :sparkles: 간편 로그인 설정
  src/apis/oauth.ts
  src/hooks/useKakaoLogin.ts
  src/pages/auth/SignIn.tsx
  src/pages/auth/redirect/kakao/index.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#91 FE-78✨댓글 수정,삭제 기능 추가
  src/apis/epigramComment.ts
  src/components/epigram/Comment/CommentItem.tsx
  src/components/epigram/Comment/CommentList.tsx
  src/components/epigram/Comment/CommentTextarea.tsx
  src/components/epigram/MoreOptionMenu.tsx
  src/hooks/useDeleteCommentHook.ts
  src/hooks/usePatchCommentHook.ts
  src/pageLayout/Epigram/EpigramComment.tsx
  src/types/epigram.types.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#72 FE-66 :twisted_rightwards_arrows: 회원가입 페이지 머지 요청
  src/apis/auth.ts
  src/hooks/useRegisterMutation.ts
  src/hooks/useSignInMutation.ts
  src/pages/auth/SignUp.tsx
  src/schema/auth.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#96 FE-29 :twisted_rightwards_arrows: [로그인 페이지] 간편 로그인 기능
  src/apis/index.ts
  src/apis/oauth.ts
  src/hooks/useKakaoLogin.ts
  src/pages/auth/SignIn.tsx
  src/pages/auth/redirect/kakao/index.tsx
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#98 FE-51 :twisted_rightwards_arrows: 공용 API 최신화 (충돌수정)
  src/apis/auth.ts
  src/hooks/useSignInMutation.ts
  src/pages/auth/SignIn.tsx
  src/schema/auth.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#92 FE-51 :twisted_rightwards_arrows: 공용 API 머지 요청
  src/apis/.http
  src/apis/epigramComment.ts
  src/apis/getEmotion.ts
  src/apis/getEpigrams.ts
  src/apis/postEmotion.ts
  src/apis/user.ts
  src/components/Emotion/EmotionCard.tsx
  src/components/Emotion/EmotionSaveToast.tsx
  src/components/Emotion/EmotionSelector.tsx
  src/hooks/useDeleteCommentHook.ts
  src/hooks/useGetEmotion.ts
  src/hooks/usePatchCommentHook.ts
  src/hooks/usePostEmotion.ts
  src/hooks/userQueryHooks.ts
  src/schema/auth.ts
  src/schema/comment.ts
  src/schema/emotion.ts
  src/schema/epigram.ts
  src/schema/epigrams.ts
  src/schema/user.ts
  src/types/emotion.ts
  src/types/epigram.types.ts
  src/utils/emotionMap.ts
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#99 FE-27 :twisted_rightwards_arrows: 브랜치 최신화
  src/apis/auth.ts
  src/apis/epigramComment.ts
  src/apis/getEmotion.ts
  src/apis/getEpigrams.ts
  src/apis/index.ts
  src/apis/oauth.ts
  src/apis/postEmotion.ts
  src/apis/user.ts
  src/components/Emotion/EmotionCard.tsx
  src/components/Emotion/EmotionSaveToast.tsx
  src/components/Emotion/EmotionSelector.tsx
  src/hooks/useDeleteCommentHook.ts
  src/hooks/useGetEmotion.ts
  src/hooks/useKakaoLogin.ts
  src/hooks/usePatchCommentHook.ts
  src/hooks/usePostEmotion.ts
  src/hooks/useRegisterMutation.ts
  src/hooks/useSignInMutation.ts
  src/hooks/userQueryHooks.ts
  src/pages/auth/SignIn.tsx
  src/pages/auth/SignUp.tsx
  src/pages/auth/redirect/kakao/index.tsx
  src/schema/auth.ts
  src/schema/comment.ts
  src/schema/emotion.ts
  src/schema/epigram.ts
  src/schema/epigrams.ts
  src/schema/user.ts
  src/types/EmotionTypes.ts
  src/types/emotion.ts
  src/types/epigram.types.ts
  src/user/ui-profile/Calendar.tsx
  src/user/ui-profile/CalendarHeader.tsx
  src/user/ui-profile/Chart.tsx
  src/user/ui-profile/EmotionMonthlyLogs.tsx
  src/utils/emotionMap.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#101 FE-13 🔀 브랜치 최신화
  public/lg.svg
  public/logo-google.svg
  public/logo-kakao.svg
  public/logo-naver.svg
  src/apis/.http
  src/apis/add.ts
  src/apis/auth.ts
  src/apis/epigramComment.ts
  src/apis/getEmotion.ts
  src/apis/getEpigrams.ts
  src/apis/index.ts
  src/apis/oauth.ts
  src/apis/postEmotion.ts
  src/apis/user.ts
  src/components/Emotion/EmotionCard.tsx
  src/components/Emotion/EmotionSaveToast.tsx
  src/components/Emotion/EmotionSelector.tsx
  src/hooks/epigramQueryHook.ts
  src/hooks/useDeleteCommentHook.ts
  src/hooks/useGetEmotion.ts
  src/hooks/useKakaoLogin.ts
  src/hooks/usePatchCommentHook.ts
  src/hooks/usePostEmotion.ts
  src/hooks/useRegisterMutation.ts
  src/hooks/useSignInMutation.ts
  src/hooks/useTagManagementHook.ts
  src/hooks/userQueryHooks.ts
  src/pageLayout/Epigram/AddEpigram.tsx
  src/pages/_app.tsx
  src/pages/addEpigram.tsx
  src/pages/auth/SignIn.tsx
  src/pages/auth/SignUp.tsx
  src/pages/auth/redirect/kakao/index.tsx
  src/schema/addEpigram.ts
  src/schema/auth.ts
  src/schema/comment.ts
  src/schema/emotion.ts
  src/schema/epigram.ts
  src/schema/epigrams.ts
  src/schema/user.ts
  src/types/emotion.ts
  src/types/epigram.types.ts
  src/utils/emotionMap.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#102 FE-27 :twisted_rightwards_arrows: 마이페이지 최신화
  src/apis/.http
  src/hooks/userQueryHooks.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#104 FE-75 ✨무한 스크롤, 검색 결과 URL에 저장 기능 구현
  src/apis/getEpigrams.ts
  src/components/search/SearchResults.tsx
  src/components/search/test.ts
  src/hooks/useGetEpigramsHooks.ts
  src/pageLayout/SearchLayout/SearchLayout.tsx
  src/pages/epigram/[id]/index.tsx
  tailwind.config.js
Labels: Priority: High 🔥, Type: Feature :sparkles:

#103 FE-41✨좋아요 기능 추가
  src/apis/epigram.ts
  src/apis/user.ts
  src/hooks/useEpigramLike.ts
  src/lib/constants.ts
  src/pageLayout/Epigram/EpigramFigure.tsx
  src/pages/epigram/[id]/index.tsx
Labels: Priority: Low 🐢, Type: Feature :sparkles:

#105 FE-32 🔀브랜치 최신화
  src/apis/add.ts
  src/apis/auth.ts
  src/apis/epigramComment.ts
  src/apis/getEmotion.ts
  src/apis/index.ts
  src/apis/oauth.ts
  src/apis/postEmotion.ts
  src/apis/user.ts
  src/components/Emotion/EmotionCard.tsx
  src/components/Emotion/EmotionSaveToast.tsx
  src/components/Emotion/EmotionSelector.tsx
  src/hooks/epigramQueryHook.ts
  src/hooks/useDeleteCommentHook.ts
  src/hooks/useGetEmotion.ts
  src/hooks/useKakaoLogin.ts
  src/hooks/usePatchCommentHook.ts
  src/hooks/usePostEmotion.ts
  src/hooks/useRegisterMutation.ts
  src/hooks/useSignInMutation.ts
  src/hooks/useTagManagementHook.ts
  src/hooks/userQueryHooks.ts
  src/pageLayout/Epigram/AddEpigram.tsx
  src/pages/addEpigram.tsx
  src/pages/auth/SignIn.tsx
  src/pages/auth/SignUp.tsx
  src/pages/auth/redirect/kakao/index.tsx
  src/schema/addEpigram.ts
  src/schema/auth.ts
  src/schema/comment.ts
  src/schema/emotion.ts
  src/schema/epigram.ts
  src/schema/user.ts
  src/types/emotion.ts
  src/types/epigram.types.ts
  src/utils/emotionMap.ts
  tailwind.config.js
Labels: Priority: High 🔥, Type: Merge :truck:

#108 FE-29 :twisted_rightwards_arrows: 브랜치 최신화
  src/apis/.http
  src/apis/auth.ts
  src/apis/epigramComment.ts
  src/apis/getEmotion.ts
  src/apis/getEpigrams.ts
  src/apis/postEmotion.ts
  src/apis/user.ts
  src/components/Emotion/EmotionCard.tsx
  src/components/Emotion/EmotionSaveToast.tsx
  src/components/Emotion/EmotionSelector.tsx
  src/hooks/useDeleteCommentHook.ts
  src/hooks/useGetEmotion.ts
  src/hooks/usePatchCommentHook.ts
  src/hooks/usePostEmotion.ts
  src/hooks/useRegisterMutation.ts
  src/hooks/useSignInMutation.ts
  src/hooks/userQueryHooks.ts
  src/pages/auth/SignUp.tsx
  src/schema/auth.ts
  src/schema/comment.ts
  src/schema/emotion.ts
  src/schema/epigram.ts
  src/schema/epigrams.ts
  src/schema/user.ts
  src/types/emotion.ts
  src/types/epigram.types.ts
  src/utils/emotionMap.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#109 FE-66 :twisted_rightwards_arrows: 브랜치 최신화
  src/apis/.http
  src/apis/epigramComment.ts
  src/apis/getEmotion.ts
  src/apis/getEpigrams.ts
  src/apis/index.ts
  src/apis/oauth.ts
  src/apis/postEmotion.ts
  src/apis/user.ts
  src/components/Emotion/EmotionCard.tsx
  src/components/Emotion/EmotionSaveToast.tsx
  src/components/Emotion/EmotionSelector.tsx
  src/hooks/useDeleteCommentHook.ts
  src/hooks/useGetEmotion.ts
  src/hooks/useKakaoLogin.ts
  src/hooks/usePatchCommentHook.ts
  src/hooks/usePostEmotion.ts
  src/hooks/userQueryHooks.ts
  src/pages/auth/SignIn.tsx
  src/pages/auth/redirect/kakao/index.tsx
  src/schema/auth.ts
  src/schema/comment.ts
  src/schema/emotion.ts
  src/schema/epigram.ts
  src/schema/epigrams.ts
  src/schema/user.ts
  src/types/emotion.ts
  src/types/epigram.types.ts
  src/utils/emotionMap.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#112 FE-32 검색페이지 메인 충돌 수정
  src/apis/.http
  tailwind.config.js
Labels: Priority: High 🔥, Type: Merge :truck:

#113 FE-27 :twisted_rightwards_arrows: 충돌에러 수정
  src/hooks/useGetEmotion.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#107 FE-32 🔀검색 페이지 메인 머지
  .vscode/settings.json
  package-lock.json
  package.json
  public/md.svg
  src/components/index.tsx
  src/components/search/RecentSearches.tsx
  src/components/search/SearchBar.tsx
  src/components/search/SearchResults.tsx
  src/hooks/useGetEpigramsHooks.ts
  src/pageLayout/SearchLayout/SearchLayout.tsx
  src/pageLayout/index.ts
  src/pages/auth/SignIn.tsx
  src/pages/search/index.tsx
  src/schema/auth.ts
  src/types/EmotionTypes.ts
  tsconfig.json
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#100 FE-27 :twisted_rightwards_arrows: 마이페이지 머지 요청
  next.config.mjs
  package-lock.json
  package.json
  public/icon/arrow-bottom-icon.svg
  public/icon/arrow-right-icon.svg
  src/apis/emotion.ts
  src/apis/index.ts
  src/apis/queries.ts
  src/apis/user.ts
  src/components/Emotion/EmotionSelector.tsx
  src/components/ui/dialog.tsx
  src/hooks/useCalendar.ts
  src/hooks/useGetEmotion.ts
  src/hooks/userQueryHooks.ts
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/pages/mypage/index.tsx
  src/schema/emotion.ts
  src/schema/user.ts
  src/types/emotion.ts
  src/types/user.ts
  src/user/ui-profile/Calendar.tsx
  src/user/ui-profile/CalendarHeader.tsx
  src/user/ui-profile/Chart.tsx
  src/user/ui-profile/EmotionMonthlyLogs.tsx
  src/user/ui-profile/Profile.tsx
  src/user/ui-profile/ProfileEdit.tsx
  src/user/utill/constants.ts
  src/user/utill/fileNameChange.ts
  tailwind.config.js
Labels: Priority: High 🔥, Type: Merge :truck:

#114 FE-27 :truck: 마이페이지 ui 관련 폴더 이동
  src/pageLayout/MypageLayout/EmotionMonthlyLogs.tsx
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/user/ui-calendar/Calendar.tsx
  src/user/ui-calendar/CalendarHeader.tsx
  src/user/ui-chart/Chart.tsx
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#115 FE-51 🔨 오늘의 감정 관련 수정
  src/apis/postEmotion.ts
  src/schema/emotion.ts
  src/utils/emotionMap.ts
Labels: Priority: High 🔥, Type: Bug :bug:

#117 FE-51 🔀 브랜치 최신화
  .vscode/settings.json
  next.config.mjs
  package-lock.json
  package.json
  public/icon/arrow-bottom-icon.svg
  public/icon/arrow-right-icon.svg
  public/md.svg
  src/apis/emotion.ts
  src/apis/index.ts
  src/apis/postEmotion.ts
  src/apis/queries.ts
  src/apis/user.ts
  src/components/Emotion/EmotionSelector.tsx
  src/components/index.tsx
  src/components/search/RecentSearches.tsx
  src/components/search/SearchBar.tsx
  src/components/search/SearchResults.tsx
  src/components/ui/dialog.tsx
  src/hooks/useCalendar.ts
  src/hooks/useGetEmotion.ts
  src/hooks/useGetEpigramsHooks.ts
  src/hooks/userQueryHooks.ts
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/pageLayout/SearchLayout/SearchLayout.tsx
  src/pageLayout/index.ts
  src/pages/auth/SignIn.tsx
  src/pages/mypage/index.tsx
  src/pages/search/index.tsx
  src/schema/emotion.ts
  src/schema/user.ts
  src/types/emotion.ts
  src/types/user.ts
  src/user/ui-profile/Calendar.tsx
  src/user/ui-profile/CalendarHeader.tsx
  src/user/ui-profile/Chart.tsx
  src/user/ui-profile/EmotionMonthlyLogs.tsx
  src/user/ui-profile/Profile.tsx
  src/user/ui-profile/ProfileEdit.tsx
  src/user/utill/constants.ts
  src/user/utill/fileNameChange.ts
  tailwind.config.js
  tsconfig.json
Labels: Priority: High 🔥, Type: Merge :truck:

#119 FE-51 🔨 공용 api 수정 및 최신화
  src/apis/postEmotion.ts
  src/schema/auth.ts
  src/schema/emotion.ts
  src/types/EmotionTypes.ts
  src/utils/emotionMap.ts
Labels: Priority: Medium :bookmark:, Type: Bug :bug:, Type: Epic :rocket:

#116 FE-54🔀 브랜치 최신화
  .vscode/settings.json
  next.config.mjs
  package-lock.json
  package.json
  public/icon/arrow-bottom-icon.svg
  public/icon/arrow-right-icon.svg
  public/md.svg
  src/apis/.http
  src/apis/auth.ts
  src/apis/emotion.ts
  src/apis/epigramComment.ts
  src/apis/getEmotion.ts
  src/apis/getEpigrams.ts
  src/apis/index.ts
  src/apis/oauth.ts
  src/apis/postEmotion.ts
  src/apis/queries.ts
  src/apis/user.ts
  src/components/Emotion/EmotionCard.tsx
  src/components/Emotion/EmotionSaveToast.tsx
  src/components/Emotion/EmotionSelector.tsx
  src/components/index.tsx
  src/components/search/RecentSearches.tsx
  src/components/search/SearchBar.tsx
  src/components/search/SearchResults.tsx
  src/components/ui/dialog.tsx
  src/hooks/useCalendar.ts
  src/hooks/useGetEmotion.ts
  src/hooks/useGetEpigramsHooks.ts
  src/hooks/useKakaoLogin.ts
  src/hooks/usePostEmotion.ts
  src/hooks/useRegisterMutation.ts
  src/hooks/useSignInMutation.ts
  src/hooks/userQueryHooks.ts
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/pageLayout/SearchLayout/SearchLayout.tsx
  src/pageLayout/index.ts
  src/pages/auth/SignIn.tsx
  src/pages/auth/SignUp.tsx
  src/pages/auth/redirect/kakao/index.tsx
  src/pages/mypage/index.tsx
  src/pages/search/index.tsx
  src/schema/auth.ts
  src/schema/emotion.ts
  src/schema/epigrams.ts
  src/schema/user.ts
  src/types/emotion.ts
  src/types/user.ts
  src/user/ui-profile/Calendar.tsx
  src/user/ui-profile/CalendarHeader.tsx
  src/user/ui-profile/Chart.tsx
  src/user/ui-profile/EmotionMonthlyLogs.tsx
  src/user/ui-profile/Profile.tsx
  src/user/ui-profile/ProfileEdit.tsx
  src/user/utill/constants.ts
  src/user/utill/fileNameChange.ts
  src/utils/emotionMap.ts
  tailwind.config.js
  tsconfig.json
Labels: Priority: High 🔥, Type: Merge :truck:

#121 FE-14 ✨ 메인페이지 ui 구현
  public/icon/FAB-icon-lg.svg
  public/icon/FAB-icon-sm.svg
  src/components/Card/CommentCard.tsx
  src/components/Card/EpigramCard.tsx
  src/components/main/FAB.tsx
  src/components/main/LoadMoreButton.tsx
  src/components/main/RecentComment.tsx
  src/components/main/RecentEpigram.tsx
  src/components/main/TodayEmotion.tsx
  src/components/main/TodayEpigram.tsx
  src/pageLayout/Epigrams/MainLayout.tsx
  src/pages/epigrams/index.tsx
Labels: Priority: High 🔥, Type: Feature :sparkles:

#123 FE-20 🔀 랜딩페이지 main merge
  public/AboutPage/ArrowDownIcon.svg
  public/AboutPage/Desktop/AboutEpigram1.png
  public/AboutPage/Desktop/AboutEpigram2.png
  public/AboutPage/Desktop/AboutEpigram3.png
  public/AboutPage/Desktop/AboutEpigram4.png
  public/AboutPage/Logo/LogoLG.svg
  public/AboutPage/Logo/LogoSM.svg
  public/AboutPage/Logo/LogoXL.svg
  public/AboutPage/Mobile/AboutEpigram1.png
  public/AboutPage/Mobile/AboutEpigram2.png
  public/AboutPage/Mobile/AboutEpigram3.png
  public/AboutPage/Mobile/AboutEpigram4.png
  public/AboutPage/Tablet/AboutEpigram1.png
  public/AboutPage/Tablet/AboutEpigram2.png
  public/AboutPage/Tablet/AboutEpigram3.png
  public/AboutPage/Tablet/AboutEpigram4.png
  src/pages/index.tsx
Labels: Priority: High 🔥, Type: Epic :rocket:

#124 FE-13 🔀 브랜치 최신화
  .vscode/settings.json
  next.config.mjs
  package-lock.json
  package.json
  public/AboutPage/ArrowDownIcon.svg
  public/AboutPage/Desktop/AboutEpigram1.png
  public/AboutPage/Desktop/AboutEpigram2.png
  public/AboutPage/Desktop/AboutEpigram3.png
  public/AboutPage/Desktop/AboutEpigram4.png
  public/AboutPage/Logo/LogoLG.svg
  public/AboutPage/Logo/LogoSM.svg
  public/AboutPage/Logo/LogoXL.svg
  public/AboutPage/Mobile/AboutEpigram1.png
  public/AboutPage/Mobile/AboutEpigram2.png
  public/AboutPage/Mobile/AboutEpigram3.png
  public/AboutPage/Mobile/AboutEpigram4.png
  public/AboutPage/Tablet/AboutEpigram1.png
  public/AboutPage/Tablet/AboutEpigram2.png
  public/AboutPage/Tablet/AboutEpigram3.png
  public/AboutPage/Tablet/AboutEpigram4.png
  public/icon/arrow-bottom-icon.svg
  public/icon/arrow-right-icon.svg
  public/md.svg
  src/apis/emotion.ts
  src/apis/index.ts
  src/apis/postEmotion.ts
  src/apis/queries.ts
  src/apis/user.ts
  src/components/Emotion/EmotionSelector.tsx
  src/components/index.tsx
  src/components/search/RecentSearches.tsx
  src/components/search/SearchBar.tsx
  src/components/search/SearchResults.tsx
  src/components/ui/dialog.tsx
  src/hooks/useCalendar.ts
  src/hooks/useGetEmotion.ts
  src/hooks/useGetEpigramsHooks.ts
  src/hooks/userQueryHooks.ts
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/pageLayout/SearchLayout/SearchLayout.tsx
  src/pageLayout/index.ts
  src/pages/auth/SignIn.tsx
  src/pages/index.tsx
  src/pages/mypage/index.tsx
  src/pages/search/index.tsx
  src/schema/emotion.ts
  src/schema/user.ts
  src/types/emotion.ts
  src/types/user.ts
  src/user/ui-profile/Calendar.tsx
  src/user/ui-profile/CalendarHeader.tsx
  src/user/ui-profile/Chart.tsx
  src/user/ui-profile/EmotionMonthlyLogs.tsx
  src/user/ui-profile/Profile.tsx
  src/user/ui-profile/ProfileEdit.tsx
  src/user/utill/constants.ts
  src/user/utill/fileNameChange.ts
  src/utils/emotionMap.ts
  tailwind.config.js
  tsconfig.json
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#126 FE-38 :sparkles: 마이페이지 내 에피그램 목록 조회
  public/none-epi.svg
  public/spinner.svg
  src/apis/queries.ts
  src/hooks/useGetEpigrams.ts
  src/pageLayout/MypageLayout/EmotionMonthlyLogs.tsx
  src/pageLayout/MypageLayout/MyContent.tsx
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/schema/epigrams.ts
  src/types/epigram.types.ts
  src/user/ui-content/MyEpigrams.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#128 FE-27 :twisted_rightwards_arrows: 마이페이지 내 에피그램 목록 main 머지 요청
  public/none-epi.svg
  public/spinner.svg
  src/apis/queries.ts
  src/hooks/useGetEpigrams.ts
  src/pageLayout/MypageLayout/EmotionMonthlyLogs.tsx
  src/pageLayout/MypageLayout/MyContent.tsx
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/schema/epigrams.ts
  src/types/epigram.types.ts
  src/user/ui-calendar/Calendar.tsx
  src/user/ui-calendar/CalendarHeader.tsx
  src/user/ui-chart/Chart.tsx
  src/user/ui-content/MyEpigrams.tsx
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#129 FE-54🔀 브랜치 최신화
  public/AboutPage/ArrowDownIcon.svg
  public/AboutPage/Desktop/AboutEpigram1.png
  public/AboutPage/Desktop/AboutEpigram2.png
  public/AboutPage/Desktop/AboutEpigram3.png
  public/AboutPage/Desktop/AboutEpigram4.png
  public/AboutPage/Logo/LogoLG.svg
  public/AboutPage/Logo/LogoSM.svg
  public/AboutPage/Logo/LogoXL.svg
  public/AboutPage/Mobile/AboutEpigram1.png
  public/AboutPage/Mobile/AboutEpigram2.png
  public/AboutPage/Mobile/AboutEpigram3.png
  public/AboutPage/Mobile/AboutEpigram4.png
  public/AboutPage/Tablet/AboutEpigram1.png
  public/AboutPage/Tablet/AboutEpigram2.png
  public/AboutPage/Tablet/AboutEpigram3.png
  public/AboutPage/Tablet/AboutEpigram4.png
  public/icon/FAB-icon-lg.svg
  public/icon/FAB-icon-sm.svg
  public/icon/plus-icon.svg
  public/none-epi.svg
  public/spinner.svg
  src/apis/getRecentComments.ts
  src/apis/getRecentEpigrams.ts
  src/apis/getTodayEpigram.ts
  src/apis/queries.ts
  src/components/Card/CommentCard.tsx
  src/components/Card/EpigramCard.tsx
  src/components/epigram/Comment/CommentItem.tsx
  src/components/epigram/Comment/CommentList.tsx
  src/components/main/FAB.tsx
  src/components/main/LoadMoreButton.tsx
  src/components/main/RecentComment.tsx
  src/components/main/RecentEpigram.tsx
  src/components/main/TodayEmotion.tsx
  src/components/main/TodayEpigram.tsx
  src/hooks/useGetEpigrams.ts
  src/hooks/useGetRecentComments.ts
  src/hooks/useGetRecentEpigrams.ts
  src/hooks/useGetTodayEpigram.ts
  src/pageLayout/Epigrams/MainLayout.tsx
  src/pageLayout/MypageLayout/EmotionMonthlyLogs.tsx
  src/pageLayout/MypageLayout/MyContent.tsx
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/pages/epigrams/index.tsx
  src/pages/index.tsx
  src/schema/epigrams.ts
  src/schema/recentEpigram.ts
  src/schema/recentcomment.ts
  src/schema/todayepigram.ts
  src/types/CommentCardTypes.ts
  src/types/epigram.types.ts
  src/user/ui-calendar/Calendar.tsx
  src/user/ui-calendar/CalendarHeader.tsx
  src/user/ui-chart/Chart.tsx
  src/user/ui-content/MyEpigrams.tsx
Labels: Priority: High 🔥, Type: Merge :truck:

#131 Fe-54♻️상세페이지 리팩토링
  src/components/epigram/EditEpigram.tsx
  src/components/epigram/MoreOptionMenu.tsx
  src/pageLayout/Epigram/AddEpigram.tsx
  src/pageLayout/Epigram/EpigramComment.tsx
  src/pages/addEpigram/index.tsx
  src/pages/epigrams/[id]/edit.tsx
  src/pages/epigrams/[id]/index.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#132 FE-54🔀상세페이지 url수정
  src/components/epigram/Comment/CommentItem.tsx
  src/components/epigram/Comment/CommentList.tsx
  src/components/epigram/EditEpigram.tsx
  src/components/epigram/MoreOptionMenu.tsx
  src/pageLayout/Epigram/AddEpigram.tsx
  src/pageLayout/Epigram/EpigramComment.tsx
  src/pages/addEpigram/index.tsx
  src/pages/epigrams/[id]/edit.tsx
  src/pages/epigrams/[id]/index.tsx
Labels: Priority: High 🔥, Type: Merge :truck:

#137 FE-27 :sparkles: 마이페이지 내 댓글목록 조회
  src/apis/epigramComment.ts
  src/apis/queries.ts
  src/apis/user.ts
  src/hooks/useCommentsHook.ts
  src/hooks/useGetMyContentHook.ts
  src/pageLayout/MypageLayout/MyContent.tsx
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/schema/user.ts
  src/user/ui-content/MyComment.tsx
Labels: Priority: High 🔥, Type: Feature :sparkles:

#136 FE-46 ✨공용 컴포넌트 헤더 업데이트
  src/components/Header/Header.tsx
  src/components/epigram/EditEpigram.tsx
  src/pageLayout/Epigram/AddEpigram.tsx
  src/pageLayout/Epigrams/MainLayout.tsx
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/pageLayout/SearchLayout/SearchLayout.tsx
  src/pages/epigrams/[id]/index.tsx
Labels: Priority: High 🔥, Type: Merge :truck:

#139 FE-29 :wrench: 로그인 뮤테이션 훅 수정
  src/hooks/useSignInMutation.ts
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:
