Repository epigram5-9/epigram, pull requests merged in 2024-08, with the labels that each got.

#141 FE-40 :sparkles: 내 댓글 수정 및 삭제 기능
  src/pageLayout/MypageLayout/MyContent.tsx
  src/user/ui-content/MyComment.tsx
  src/user/ui-content/MyEpigrams.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#143 FE-24 ✨ Page location 기능
  package-lock.json
  src/pageLayout/About/AboutPageLayout.tsx
  src/pageLayout/About/StartButton.tsx
  src/pages/index.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#148 FE-27 :twisted_rightwards_arrows: 브랜치 최신화
  src/apis/queries.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#146 FE-54♻️상세페이지 개선사항 적용
  public/icon/privateIcon.png
  public/icon/publicIcon.png
  public/noComment.svg
  src/components/epigram/Comment/CommentItem.tsx
  src/components/epigram/Comment/NoComment.tsx
  src/components/ui/switch.tsx
  src/hooks/useAddEpigramHook.ts
  src/hooks/usePostCommentHook.ts
  src/pageLayout/Epigram/AddEpigram.tsx
  src/pageLayout/Epigram/EpigramComment.tsx
  src/pages/epigrams/[id]/index.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#150 FE-21 :lipstick: 반응형 디자인 구현
  src/pageLayout/About/AboutPageLayout.tsx
  src/pageLayout/About/StartButton.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#153 FE-17 :bug: 최신 에피그램 더보기 조회 기능 수정
  public/spinner.svg
  src/apis/getRecentEpigrams.ts
  src/components/main/RecentEpigram.tsx
  src/hooks/useGetRecentEpigrams.ts
  src/schema/recentEpigram.ts
Labels: Priority: Medium :bookmark:, Type: Bug :bug:

#155 FE-16 :bug: 오늘의 감정 저장 기능 수정
  src/components/Emotion/EmotionSelector.tsx
  src/components/main/TodayEmotion.tsx
  src/components/ui/toast.tsx
Labels: Priority: Medium :bookmark:, Type: Bug :bug:

#149 FE-35 :sparkles: 마이페이지 오늘의 감정 컴포넌트 연동
  src/components/main/TodayEmotion.tsx
  src/pageLayout/MypageLayout/MyPageLayout.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#156 FE-13 🐛 메인 페이지 테스트 기반 오류 수정
  package-lock.json
  src/apis/getRecentComments.ts
  src/apis/getRecentEpigrams.ts
  src/components/Card/CommentCard.tsx
  src/components/Emotion/EmotionSelector.tsx
  src/components/main/RecentComment.tsx
  src/components/main/RecentEpigram.tsx
  src/components/main/TodayEmotion.tsx
  src/components/main/TodayEpigram.tsx
  src/components/ui/toast.tsx
  src/hooks/useGetRecentComments.ts
  src/hooks/useGetRecentEpigrams.ts
  src/schema/recentEpigram.ts
Labels: Priority: Medium :bookmark:, Type: Bug :bug:, Type: Epic :rocket:

#160 FE-29 :twisted_rightwards_arrows: 브랜치 최신화
  package-lock.json
  src/apis/getRecentComments.ts
  src/apis/getRecentEpigrams.ts
  src/components/Card/CommentCard.tsx
  src/components/Emotion/EmotionSelector.tsx
  src/components/Header/Header.tsx
  src/components/epigram/EditEpigram.tsx
  src/components/main/RecentComment.tsx
  src/components/main/RecentEpigram.tsx
  src/components/main/TodayEmotion.tsx
  src/components/main/TodayEpigram.tsx
  src/components/ui/toast.tsx
  src/hooks/useGetRecentComments.ts
  src/hooks/useGetRecentEpigrams.ts
  src/pageLayout/About/AboutPageLayout.tsx
  src/pageLayout/About/StartButton.tsx
  src/pageLayout/Epigram/AddEpigram.tsx
  src/pageLayout/Epigrams/MainLayout.tsx
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/pageLayout/SearchLayout/SearchLayout.tsx
  src/pages/epigrams/[id]/index.tsx
  src/pages/index.tsx
  src/schema/recentEpigram.ts
  tailwind.config.js
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#159 FE-66 :recycle: 회원가입 페이지 수정
  public/horizen.png
  src/components/ui/input.tsx
  src/components/ui/textarea.tsx
  src/hooks/useRegisterMutation.ts
  src/pages/auth/SignUp.tsx
  src/schema/auth.ts
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#164 FE-83 ✨ 피드 페이지 구현
  public/icon/grid-icon.svg
  public/icon/sort-icon.svg
  src/components/main/FAB.tsx
  src/pageLayout/Feed/AddEpigramFAB.tsx
  src/pageLayout/Feed/EpigramFeed.tsx
  src/pageLayout/Feed/FeedCard.tsx
  src/pageLayout/Feed/FeedPageLayout.tsx
  src/pageLayout/Feed/MoreEpigramButton.tsx
  src/pages/feed/index.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Improve UX :arrow_up:

#167 FE-29 :twisted_rightwards_arrows: 브랜치 최신화
  public/horizen.png
  src/components/ui/input.tsx
  src/components/ui/textarea.tsx
  src/hooks/useRegisterMutation.ts
  src/pages/auth/SignUp.tsx
  src/schema/auth.ts
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#163 FE-54✨ 댓글 수정 로직 변경
  src/components/epigram/Comment/CommentItem.tsx
  src/components/epigram/Comment/CommentList.tsx
  src/components/epigram/Comment/CommentTextarea.tsx
  src/pageLayout/Epigram/EpigramComment.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#165 FE-83 ✨ 피드 페이지 구현
  public/icon/grid-icon.svg
  public/icon/sort-icon.svg
  src/components/main/FAB.tsx
  src/pageLayout/Feed/AddEpigramFAB.tsx
  src/pageLayout/Feed/EpigramFeed.tsx
  src/pageLayout/Feed/FeedCard.tsx
  src/pageLayout/Feed/FeedPageLayout.tsx
  src/pageLayout/Feed/MoreEpigramButton.tsx
  src/pages/feed/index.tsx
Labels: Priority: High 🔥, Type: Epic :rocket:

#170 FE-29 :twisted_rightwards_arrows: 브랜치 최신화
  public/icon/grid-icon.svg
  public/icon/sort-icon.svg
  src/components/main/FAB.tsx
  src/pageLayout/Feed/AddEpigramFAB.tsx
  src/pageLayout/Feed/EpigramFeed.tsx
  src/pageLayout/Feed/FeedCard.tsx
  src/pageLayout/Feed/FeedPageLayout.tsx
  src/pageLayout/Feed/MoreEpigramButton.tsx
  src/pages/feed/index.tsx
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#169 FE-54♻️ 좋아요 기능 리팩토링, Query Key 분리
  public/unlikeIcon.svg
  src/apis/queries.ts
  src/components/epigram/Comment/CommentTextarea.tsx
  src/hooks/useEpigramCommentsQueryHook.ts
  src/hooks/useEpigramLike.ts
  src/pageLayout/Epigram/EpigramComment.tsx
  src/pageLayout/Epigram/EpigramFigure.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#173 FE-50 ✨ 두번째 헤더 구현
  fonts/montserrat/Montserrat-Regular.woff2
  public/icon/menu-icon.svg
  public/icon/user-icon.svg
  public/icon/x-icon.svg
  src/components/Header/Header.tsx
  src/components/Header/NewHeader.tsx
  src/components/Header/SideBar.tsx
  src/pageLayout/About/AboutPageLayout.tsx
  src/pageLayout/Epigram/AddEpigram.tsx
  src/pageLayout/Epigrams/MainLayout.tsx
  src/pageLayout/Feed/FeedPageLayout.tsx
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/pageLayout/SearchLayout/SearchLayout.tsx
  src/styles/globals.css
  src/types/Header.ts
  tailwind.config.js
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#174 FE-46 ✨ 두번째 헤더 구현
  fonts/montserrat/Montserrat-Regular.woff2
  public/icon/menu-icon.svg
  public/icon/user-icon.svg
  public/icon/x-icon.svg
  src/components/Header/Header.tsx
  src/components/Header/NewHeader.tsx
  src/components/Header/SideBar.tsx
  src/pageLayout/About/AboutPageLayout.tsx
  src/pageLayout/Epigram/AddEpigram.tsx
  src/pageLayout/Epigrams/MainLayout.tsx
  src/pageLayout/Feed/FeedPageLayout.tsx
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/pageLayout/SearchLayout/SearchLayout.tsx
  src/styles/globals.css
  src/types/Header.ts
  tailwind.config.js
Labels: Priority: Medium :bookmark:, Type: Epic :rocket:

#177 FE-35 :recycle: 마이페이지 내 에피그램/댓글 선택 버튼컴포넌트로 변경
  src/pageLayout/MypageLayout/MyContent.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#158 FE-27 :sparkles: 마이페이지 오늘의 감정 선택 main 머지 요청
  src/apis/epigramComment.ts
  src/apis/queries.ts
  src/apis/user.ts
  src/hooks/useCommentsHook.ts
  src/hooks/useGetMyContentHook.ts
  src/pageLayout/MypageLayout/MyContent.tsx
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/schema/user.ts
  src/user/ui-content/MyComment.tsx
  src/user/ui-content/MyEpigrams.tsx
  src/user/ui-profile/Calendar.tsx
  src/user/ui-profile/CalendarHeader.tsx
  src/user/ui-profile/Chart.tsx
  src/user/ui-profile/EmotionMonthlyLogs.tsx
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#175 FE-32 검색 페이지 무한 스크롤 오류 수정
  package-lock.json
  src/components/Header/Header.tsx
  src/components/search/SearchResults.tsx
  src/hooks/useGetEpigramsHooks.ts
  src/pageLayout/MypageLayout/EmotionMonthlyLogs.tsx
  src/pageLayout/MypageLayout/MyContent.tsx
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/pageLayout/SearchLayout/SearchLayout.tsx
  src/pages/mypage/index.tsx
  src/schema/epigrams.ts
Labels: Priority: High 🔥, Type: Refactor :recycle:

#180 FE-81 :recycle: 마이페이지 프로필 수정 기능 리팩토링
  src/components/mypage/Calendar.tsx
  src/components/mypage/CalendarHeader.tsx
  src/components/mypage/Chart.tsx
  src/components/mypage/MyComment.tsx
  src/components/mypage/MyEpigrams.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/ProfileEdit.tsx
  src/hooks/userQueryHooks.ts
  src/pageLayout/MypageLayout/EmotionMonthlyLogs.tsx
  src/pageLayout/MypageLayout/MyContent.tsx
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/schema/user.ts
  src/user/ui-profile/ProfileEdit.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#182 FE-54 🔀 브랜치 최신화
  fonts/montserrat/Montserrat-Regular.woff2
  public/icon/menu-icon.svg
  public/icon/user-icon.svg
  public/icon/x-icon.svg
  src/apis/epigramComment.ts
  src/apis/queries.ts
  src/apis/user.ts
  src/components/Header/Header.tsx
  src/components/Header/NewHeader.tsx
  src/components/Header/SideBar.tsx
  src/components/epigram/EditEpigram.tsx
  src/hooks/useCommentsHook.ts
  src/hooks/useGetMyContentHook.ts
  src/pageLayout/About/AboutPageLayout.tsx
  src/pageLayout/Epigram/AddEpigram.tsx
  src/pageLayout/Epigrams/MainLayout.tsx
  src/pageLayout/Feed/FeedPageLayout.tsx
  src/pageLayout/MypageLayout/MyContent.tsx
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/pageLayout/SearchLayout/SearchLayout.tsx
  src/pages/epigrams/[id]/index.tsx
  src/schema/user.ts
  src/styles/globals.css
  src/types/Header.ts
  src/user/ui-content/MyComment.tsx
  src/user/ui-content/MyEpigrams.tsx
  src/user/ui-profile/Calendar.tsx
  src/user/ui-profile/CalendarHeader.tsx
  src/user/ui-profile/Chart.tsx
  src/user/ui-profile/EmotionMonthlyLogs.tsx
  tailwind.config.js
Labels: Priority: High 🔥, Type: Merge :truck:

#172 FE-54🔀 상세페이지 리팩토링 main머지
  public/icon/privateIcon.png
  public/icon/publicIcon.png
  public/noComment.svg
  public/unlikeIcon.svg
  src/apis/queries.ts
  src/components/epigram/Comment/CommentItem.tsx
  src/components/epigram/Comment/CommentList.tsx
  src/components/epigram/Comment/CommentTextarea.tsx
  src/components/epigram/Comment/NoComment.tsx
  src/components/epigram/EditEpigram.tsx
  src/components/ui/switch.tsx
  src/hooks/useAddEpigramHook.ts
  src/hooks/useEpigramCommentsQueryHook.ts
  src/hooks/useEpigramLike.ts
  src/hooks/usePostCommentHook.ts
  src/pageLayout/Epigram/AddEpigram.tsx
  src/pageLayout/Epigram/EpigramComment.tsx
  src/pageLayout/Epigram/EpigramFigure.tsx
  src/pages/epigrams/[id]/index.tsx
Labels: Priority: High 🔥, Type: Merge :truck:

#183 FE-27 :twisted_rightwards_arrows: 마이페이지 브랜치 최신화
  public/icon/privateIcon.png
  public/icon/publicIcon.png
  public/noComment.svg
  public/unlikeIcon.svg
  src/apis/queries.ts
  src/components/epigram/Comment/CommentItem.tsx
  src/components/epigram/Comment/CommentList.tsx
  src/components/epigram/Comment/CommentTextarea.tsx
  src/components/epigram/Comment/NoComment.tsx
  src/components/epigram/EditEpigram.tsx
  src/components/ui/switch.tsx
  src/hooks/useAddEpigramHook.ts
  src/hooks/useEpigramCommentsQueryHook.ts
  src/hooks/useEpigramLike.ts
  src/hooks/usePostCommentHook.ts
  src/pageLayout/Epigram/AddEpigram.tsx
  src/pageLayout/Epigram/EpigramComment.tsx
  src/pageLayout/Epigram/EpigramFigure.tsx
  src/pages/epigrams/[id]/index.tsx
Labels: Priority: High 🔥, Type: Merge :truck:

#187 FE-29 :twisted_rightwards_arrows: 브랜치 최신화
  fonts/montserrat/Montserrat-Regular.woff2
  public/icon/menu-icon.svg
  public/icon/privateIcon.png
  public/icon/publicIcon.png
  public/icon/user-icon.svg
  public/icon/x-icon.svg
  public/noComment.svg
  public/unlikeIcon.svg
  src/apis/epigramComment.ts
  src/apis/queries.ts
  src/apis/user.ts
  src/components/Header/Header.tsx
  src/components/Header/NewHeader.tsx
  src/components/Header/SideBar.tsx
  src/components/epigram/Comment/CommentItem.tsx
  src/components/epigram/Comment/CommentList.tsx
  src/components/epigram/Comment/CommentTextarea.tsx
  src/components/epigram/Comment/NoComment.tsx
  src/components/epigram/EditEpigram.tsx
  src/components/ui/switch.tsx
  src/hooks/useAddEpigramHook.ts
  src/hooks/useCommentsHook.ts
  src/hooks/useEpigramCommentsQueryHook.ts
  src/hooks/useEpigramLike.ts
  src/hooks/useGetMyContentHook.ts
  src/hooks/usePostCommentHook.ts
  src/pageLayout/About/AboutPageLayout.tsx
  src/pageLayout/Epigram/AddEpigram.tsx
  src/pageLayout/Epigram/EpigramComment.tsx
  src/pageLayout/Epigram/EpigramFigure.tsx
  src/pageLayout/Epigrams/MainLayout.tsx
  src/pageLayout/Feed/FeedPageLayout.tsx
  src/pageLayout/MypageLayout/MyContent.tsx
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/pageLayout/SearchLayout/SearchLayout.tsx
  src/pages/epigrams/[id]/index.tsx
  src/schema/user.ts
  src/styles/globals.css
  src/types/Header.ts
  src/user/ui-content/MyComment.tsx
  src/user/ui-content/MyEpigrams.tsx
  src/user/ui-profile/Calendar.tsx
  src/user/ui-profile/CalendarHeader.tsx
  src/user/ui-profile/Chart.tsx
  src/user/ui-profile/EmotionMonthlyLogs.tsx
  tailwind.config.js
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#185 FE-29 :wrench: 구글 소셜 로그인 수정
  next.config.mjs
  src/apis/index.ts
  src/apis/postGoogleOauth.ts
  src/hooks/useGoogleLogin.ts
  src/hooks/useSignInMutation.ts
  src/pages/auth/SignIn.tsx
  src/pages/auth/callback/google/index.ts
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#186 FE-54🐛 댓글 불러오지못하는 문제 해결
  src/apis/queries.ts
  src/hooks/useEpigramCommentsQueryHook.ts
  src/hooks/usePatchCommentHook.ts
  src/hooks/usePostCommentHook.ts
  src/pageLayout/Epigram/EpigramFigure.tsx
Labels: Priority: Medium :bookmark:, Type: Bug :bug:

#189 FE-32 브랜치 최신화
  src/apis/queries.ts
  src/pageLayout/MypageLayout/EmotionMonthlyLogs.tsx
  src/pageLayout/MypageLayout/MyContent.tsx
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/pages/mypage/index.tsx
  tailwind.config.js
Labels: Priority: High 🔥, Type: Merge :truck:

#178 FE-32 🔀 검색페이지 오류 수정
  .eslintrc.js
  src/apis/.http
  src/components/search/SearchResults.tsx
  src/hooks/useGetEpigramsHooks.ts
  src/pageLayout/MypageLayout/MyContent.tsx
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/pageLayout/SearchLayout/SearchLayout.tsx
  src/pages/mypage/index.tsx
  src/schema/auth.ts
  src/schema/epigrams.ts
  src/types/EmotionTypes.ts
  src/user/ui-profile/Calendar.tsx
  src/user/ui-profile/CalendarHeader.tsx
  src/user/ui-profile/Chart.tsx
  src/user/ui-profile/EmotionMonthlyLogs.tsx
  tailwind.config.js
Labels: Priority: High 🔥, Type: Merge :truck:

#192 FE-84 :recycle: 마이페이지 감정 달력 코드 리팩토링
  src/components/main/TodayEmotion.tsx
  src/components/mypage/Calendar.tsx
  src/components/mypage/CalendarHeader.tsx
  src/context/EmotionContext.tsx
  src/hooks/useGetEmotion.ts
  src/pageLayout/MypageLayout/EmotionMonthlyLogs.tsx
  src/pageLayout/MypageLayout/MyPageLayout.tsx
Labels: Priority: High 🔥, Type: Refactor :recycle:

#188 FE-29 :wrench: 구글 간편 로그인 수정
  next.config.mjs
  src/apis/index.ts
  src/apis/postGoogleOauth.ts
  src/hooks/useGoogleLogin.ts
  src/hooks/useSignInMutation.ts
  src/pages/auth/SignIn.tsx
  src/pages/auth/callback/google/index.ts
Labels: Priority: Medium :bookmark:, Type: Merge :truck:, Type: Refactor :recycle:

#194 FE-27 :twisted_rightwards_arrows: 마이페이지 브랜치 최신화
  .eslintrc.js
  src/apis/.http
  src/apis/queries.ts
  src/components/search/SearchResults.tsx
  src/hooks/useEpigramCommentsQueryHook.ts
  src/hooks/useGetEpigramsHooks.ts
  src/hooks/usePatchCommentHook.ts
  src/hooks/usePostCommentHook.ts
  src/pageLayout/Epigram/EpigramFigure.tsx
  src/pageLayout/SearchLayout/SearchLayout.tsx
  src/schema/auth.ts
  src/schema/epigrams.ts
  src/types/EmotionTypes.ts
  src/types/epigram.types.ts
  tailwind.config.js
Labels: Priority: High 🔥, Type: Merge :truck:

#195 FE-27 :twisted_rightwards_arrows: 마이페이지 브랜치 최신화
  next.config.mjs
  src/apis/index.ts
  src/apis/postGoogleOauth.ts
  src/apis/queries.ts
  src/hooks/useGoogleLogin.ts
  src/hooks/useSignInMutation.ts
  src/pages/auth/SignIn.tsx
  src/pages/auth/callback/google/index.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#181 FE-27 :recycle: 마이페이지 프로필 수정 기능 리팩토링
  src/components/main/TodayEmotion.tsx
  src/components/mypage/Calendar.tsx
  src/components/mypage/CalendarHeader.tsx
  src/components/mypage/Chart.tsx
  src/components/mypage/MyComment.tsx
  src/components/mypage/MyEpigrams.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/ProfileEdit.tsx
  src/context/EmotionContext.tsx
  src/hooks/useEpigramCommentsQueryHook.ts
  src/hooks/useGetEmotion.ts
  src/hooks/userQueryHooks.ts
  src/pageLayout/MypageLayout/EmotionMonthlyLogs.tsx
  src/pageLayout/MypageLayout/MyContent.tsx
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/schema/user.ts
  src/types/epigram.types.ts
  src/user/ui-profile/Calendar.tsx
  src/user/ui-profile/CalendarHeader.tsx
  src/user/ui-profile/Chart.tsx
  src/user/ui-profile/ProfileEdit.tsx
Labels: Priority: High 🔥, Type: Refactor :recycle:

#196 FE-29 :twisted_rightwards_arrows: 브랜치 최신화
  .eslintrc.js
  src/apis/.http
  src/apis/queries.ts
  src/components/main/TodayEmotion.tsx
  src/components/mypage/Calendar.tsx
  src/components/mypage/CalendarHeader.tsx
  src/components/mypage/Chart.tsx
  src/components/mypage/MyComment.tsx
  src/components/mypage/MyEpigrams.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/ProfileEdit.tsx
  src/components/search/SearchResults.tsx
  src/context/EmotionContext.tsx
  src/hooks/useEpigramCommentsQueryHook.ts
  src/hooks/useGetEmotion.ts
  src/hooks/useGetEpigramsHooks.ts
  src/hooks/usePatchCommentHook.ts
  src/hooks/usePostCommentHook.ts
  src/hooks/userQueryHooks.ts
  src/pageLayout/Epigram/EpigramFigure.tsx
  src/pageLayout/MypageLayout/EmotionMonthlyLogs.tsx
  src/pageLayout/MypageLayout/MyContent.tsx
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/pageLayout/SearchLayout/SearchLayout.tsx
  src/pages/mypage/index.tsx
  src/schema/auth.ts
  src/schema/epigrams.ts
  src/schema/user.ts
  src/types/EmotionTypes.ts
  src/types/epigram.types.ts
  src/user/ui-profile/ProfileEdit.tsx
  tailwind.config.js
Labels: Priority: Low 🐢, Type: Merge :truck:

#197 FE-29 :recycle: 로그인 페이지 리팩토링
  src/apis/index.ts
  src/apis/postGoogleOauth.ts
  src/pages/auth/SignIn.tsx
  src/pages/auth/SignUp.tsx
  src/pages/auth/callback/google/index.ts
  src/pages/auth/redirect/google-callback/index.ts
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#198 FE-85 :recycle: 마이페이지 감정차트 리팩토링
  package-lock.json
  package.json
  src/components/mypage/Chart.tsx
  src/pages/mypage/index.tsx
Labels: Priority: High 🔥, Type: Refactor :recycle:

#200 FE-27 :twisted_rightwards_arrows: 마이페이지 감정 차트 리팩토링 main 머지
  package-lock.json
  package.json
  src/components/mypage/Chart.tsx
  src/pages/mypage/index.tsx
Labels: Priority: High 🔥, Type: Merge :truck:

#199 FE-29 :recycle: 로그인페이지 리팩토링
  src/apis/index.ts
  src/apis/postGoogleOauth.ts
  src/pages/auth/SignIn.tsx
  src/pages/auth/SignUp.tsx
  src/pages/auth/callback/google/index.ts
  src/pages/auth/redirect/google-callback/index.ts
Labels: Priority: High 🔥, Type: Merge :truck:, Type: Refactor :recycle:

#202 FE-54🔀 브랜치 최신화
  .eslintrc.js
  next.config.mjs
  package-lock.json
  package.json
  src/apis/.http
  src/apis/index.ts
  src/apis/postGoogleOauth.ts
  src/components/main/TodayEmotion.tsx
  src/components/mypage/Calendar.tsx
  src/components/mypage/CalendarHeader.tsx
  src/components/mypage/Chart.tsx
  src/components/mypage/MyComment.tsx
  src/components/mypage/MyEpigrams.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/ProfileEdit.tsx
  src/components/search/SearchResults.tsx
  src/context/EmotionContext.tsx
  src/hooks/useGetEmotion.ts
  src/hooks/useGetEpigramsHooks.ts
  src/hooks/useGoogleLogin.ts
  src/hooks/useSignInMutation.ts
  src/hooks/userQueryHooks.ts
  src/pageLayout/MypageLayout/EmotionMonthlyLogs.tsx
  src/pageLayout/MypageLayout/MyContent.tsx
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/pageLayout/SearchLayout/SearchLayout.tsx
  src/pages/auth/SignIn.tsx
  src/pages/auth/SignUp.tsx
  src/pages/auth/callback/google/index.ts
  src/schema/auth.ts
  src/schema/epigrams.ts
  src/schema/user.ts
  src/types/EmotionTypes.ts
  src/types/epigram.types.ts
  src/user/ui-chart/Chart.tsx
  src/user/ui-profile/ProfileEdit.tsx
  tailwind.config.js
Labels: Priority: High 🔥, Type: Merge :truck:

#207 FE-48 :lipstick: ui 수정
  src/components/main/FAB.tsx
  src/pageLayout/About/AboutPageLayout.tsx
  src/pageLayout/Epigrams/MainLayout.tsx
  src/pageLayout/Feed/AddEpigramFAB.tsx
Labels: Priority: Low 🐢, Type: Improve UX :arrow_up:

#204 FE-77✨ 댓글 프로필 모달 추가
  src/components/Card/UserProfileModal.tsx
  src/components/epigram/Comment/CommentItem.tsx
  src/components/ui/dialog_dim.tsx
  src/pageLayout/Epigram/EpigramFigure.tsx
Labels: Priority: High 🔥, Type: Feature :sparkles:

#209 FE-27 :twisted_rightwards_arrows: 마이페이지 브랜치 최신화
  src/apis/index.ts
  src/apis/postGoogleOauth.ts
  src/components/Card/UserProfileModal.tsx
  src/components/epigram/Comment/CommentItem.tsx
  src/components/main/FAB.tsx
  src/components/ui/dialog_dim.tsx
  src/hooks/useDeleteCommentHook.ts
  src/hooks/useEpigramCommentsQueryHook.ts
  src/pageLayout/About/AboutPageLayout.tsx
  src/pageLayout/Epigram/EpigramFigure.tsx
  src/pageLayout/Epigrams/MainLayout.tsx
  src/pageLayout/Feed/AddEpigramFAB.tsx
  src/pageLayout/MypageLayout/MyContent.tsx
  src/pages/auth/SignIn.tsx
  src/pages/auth/SignUp.tsx
  src/pages/auth/callback/google/index.ts
  src/pages/auth/redirect/google-callback/index.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#210 FE-29 :twisted_rightwards_arrows: 브랜치 최신화
  package-lock.json
  package.json
  src/components/Card/UserProfileModal.tsx
  src/components/epigram/Comment/CommentItem.tsx
  src/components/main/FAB.tsx
  src/components/mypage/Chart.tsx
  src/components/ui/dialog_dim.tsx
  src/hooks/useDeleteCommentHook.ts
  src/hooks/useEpigramCommentsQueryHook.ts
  src/pageLayout/About/AboutPageLayout.tsx
  src/pageLayout/Epigram/EpigramFigure.tsx
  src/pageLayout/Epigrams/MainLayout.tsx
  src/pageLayout/Feed/AddEpigramFAB.tsx
  src/pageLayout/MypageLayout/MyContent.tsx
  src/pages/mypage/index.tsx
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#211 FE-29 :wrench: 로그인 페이지 수정
  src/apis/auth.ts
  src/hooks/useRefreshToken.ts
  src/pages/auth/SignIn.tsx
  src/pages/auth/SignUp.tsx
  src/schema/auth.ts
Labels: Priority: High 🔥, Type: Bug :bug:, Type: Refactor :recycle:

#212 FE-29 :twisted_rightwards_arrows: 로그인 페이지 수정
  src/apis/auth.ts
  src/hooks/useRefreshToken.ts
  src/pages/auth/SignIn.tsx
  src/pages/auth/SignUp.tsx
  src/schema/auth.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#213 FE-86 :recycle: 마이페이지 내 댓글목록 조회 코드 리팩토링
  src/apis/user.ts
  src/components/epigram/Comment/CommentItem.tsx
  src/components/mypage/MyComment.tsx
  src/hooks/useCommentsHook.ts
  src/hooks/useDeleteCommentHook.ts
  src/pageLayout/MypageLayout/MyContent.tsx
Labels: Priority: High 🔥, Type: Refactor :recycle:

#214 FE-27 :twisted_rightwards_arrows: 마이페이지 브랜치 최신화
  src/apis/auth.ts
  src/hooks/useRefreshToken.ts
  src/pages/auth/SignIn.tsx
  src/pages/auth/SignUp.tsx
  src/schema/auth.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#215 FE-27 :sparkles: 로그아웃 버튼 추가
  src/components/Header/NewHeader.tsx
Labels: Priority: High 🔥, Type: Feature :sparkles:

#217 FE-27 :bug: prettier 에러 수정
  src/pageLayout/MypageLayout/MyContent.tsx
Labels: Priority: High 🔥, Type: Bug :bug:

#216 FE-27 :twisted_rightwards_arrows: 마이페이지 메인 머지
  src/apis/user.ts
  src/components/Header/NewHeader.tsx
  src/components/epigram/Comment/CommentItem.tsx
  src/components/mypage/MyComment.tsx
  src/hooks/useCommentsHook.ts
  src/hooks/useDeleteCommentHook.ts
  src/pageLayout/MypageLayout/MyContent.tsx
Labels: Priority: High 🔥, Type: Merge :truck:

#219 FE-54🔀 브랜치 최신화
  src/apis/auth.ts
  src/apis/user.ts
  src/components/Header/NewHeader.tsx
  src/components/epigram/Comment/CommentItem.tsx
  src/components/main/FAB.tsx
  src/components/mypage/MyComment.tsx
  src/hooks/useCommentsHook.ts
  src/hooks/useDeleteCommentHook.ts
  src/hooks/useRefreshToken.ts
  src/pageLayout/About/AboutPageLayout.tsx
  src/pageLayout/Epigrams/MainLayout.tsx
  src/pageLayout/Feed/AddEpigramFAB.tsx
  src/pageLayout/MypageLayout/MyContent.tsx
  src/pages/auth/SignIn.tsx
  src/pages/auth/SignUp.tsx
  src/schema/auth.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#222 FE-13 💄 메인 페이지 ui 수정
  package-lock.json
  public/spinner.svg
  src/components/main/FAB.tsx
  src/components/main/RecentComment.tsx
Labels: Priority: Medium :bookmark:, Type: Epic :rocket:, Type: Improve UX :arrow_up:

#223 FE-54♻️ 피드백 반영
  src/components/epigram/Comment/CommentItem.tsx
  src/components/epigram/EditEpigram.tsx
  src/components/epigram/MoreOptionMenu.tsx
  src/hooks/useEpigramCommentsQueryHook.ts
  src/hooks/useTagManagementHook.ts
  src/pageLayout/Epigram/AddEpigram.tsx
  src/pageLayout/Epigram/EpigramComment.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#224 FE-54🔀 브랜치 최신화
  package-lock.json
  public/spinner.svg
  src/components/main/FAB.tsx
  src/components/main/RecentComment.tsx
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#226 FE-88 ✨ 오늘의 에피그램 상세페이지 연결
  src/components/main/TodayEpigram.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#225 FE-54♻️ 피드백 반영 main 머지
  src/components/epigram/Comment/CommentItem.tsx
  src/components/epigram/EditEpigram.tsx
  src/components/epigram/MoreOptionMenu.tsx
  src/hooks/useEpigramCommentsQueryHook.ts
  src/hooks/useTagManagementHook.ts
  src/pageLayout/Epigram/AddEpigram.tsx
  src/pageLayout/Epigram/EpigramComment.tsx
Labels: Priority: High 🔥, Type: Merge :truck:

#228 FE-29 :recycle: 로그인 페이지 리팩토링
  src/apis/oauth.ts
  src/apis/postKakaoOauth.ts
  src/hooks/useKakaoLogin.ts
  src/hooks/useRegisterMutation.ts
  src/pages/auth/SignIn.tsx
  src/pages/auth/SignUp.tsx
Labels: Priority: High 🔥, Type: Refactor :recycle:

#231 FE-32 TODO 주석 제거 및 뉴헤더 스타일 수정
  package-lock.json
  package.json
  src/components/Header/NewHeader.tsx
  src/components/search/SearchBar.tsx
  src/components/search/SearchResults.tsx
  src/pages/mypage/index.tsx
Labels: Priority: High 🔥, Type: Improve UX :arrow_up:

#233 FE-27 :twisted_rightwards_arrows: 브랜치 최신화
  package-lock.json
  package.json
  public/spinner.svg
  src/apis/oauth.ts
  src/apis/postKakaoOauth.ts
  src/components/Header/NewHeader.tsx
  src/components/epigram/Comment/CommentItem.tsx
  src/components/epigram/EditEpigram.tsx
  src/components/epigram/MoreOptionMenu.tsx
  src/components/main/FAB.tsx
  src/components/main/RecentComment.tsx
  src/components/main/TodayEpigram.tsx
  src/components/search/SearchBar.tsx
  src/components/search/SearchResults.tsx
  src/hooks/useEpigramCommentsQueryHook.ts
  src/hooks/useKakaoLogin.ts
  src/hooks/useRegisterMutation.ts
  src/hooks/useTagManagementHook.ts
  src/pageLayout/Epigram/AddEpigram.tsx
  src/pageLayout/Epigram/EpigramComment.tsx
  src/pages/auth/SignIn.tsx
  src/pages/auth/SignUp.tsx
  src/pages/mypage/index.tsx
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#234 FE-89 :recycle: 마이페이지 내 에피그램 목록조회 리팩토링
  src/components/mypage/Calendar.tsx
  src/components/mypage/Chart.tsx
  src/components/mypage/Profile.tsx
  src/hooks/useMyContentState.tsx
  src/pageLayout/MypageLayout/MyContent.tsx
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/pages/mypage/index.tsx
Labels: Priority: High 🔥, Type: Refactor :recycle:

#235 FE-27 :recycle: 내 에피그램 목록조회 리팩토링
  src/components/mypage/Calendar.tsx
  src/components/mypage/Chart.tsx
  src/components/mypage/Profile.tsx
  src/hooks/useMyContentState.tsx
  src/pageLayout/MypageLayout/MyContent.tsx
  src/pageLayout/MypageLayout/MyPageLayout.tsx
Labels: Priority: High 🔥, Type: Merge :truck:

#236 FE-13 :twisted_rightwards_arrows: 메인페이지 브랜치 최신화
  package-lock.json
  package.json
  src/apis/oauth.ts
  src/apis/postKakaoOauth.ts
  src/components/Header/NewHeader.tsx
  src/components/epigram/Comment/CommentItem.tsx
  src/components/epigram/EditEpigram.tsx
  src/components/epigram/MoreOptionMenu.tsx
  src/components/mypage/Calendar.tsx
  src/components/mypage/Chart.tsx
  src/components/mypage/Profile.tsx
  src/components/search/SearchBar.tsx
  src/components/search/SearchResults.tsx
  src/hooks/useEpigramCommentsQueryHook.ts
  src/hooks/useKakaoLogin.ts
  src/hooks/useMyContentState.tsx
  src/hooks/useRegisterMutation.ts
  src/hooks/useTagManagementHook.ts
  src/pageLayout/Epigram/AddEpigram.tsx
  src/pageLayout/Epigram/EpigramComment.tsx
  src/pageLayout/MypageLayout/MyContent.tsx
  src/pageLayout/MypageLayout/MyPageLayout.tsx
  src/pages/auth/SignIn.tsx
  src/pages/auth/SignUp.tsx
  src/pages/mypage/index.tsx
Labels: Priority: High 🔥, Type: Merge :truck:

#237 FE-91 :bug: 메인페이지 에피그램 및 댓글목록 중복오류 수정
  src/components/main/RecentComment.tsx
  src/components/main/RecentEpigram.tsx
  src/pages/mypage/index.tsx
Labels: Priority: High 🔥, Type: Bug :bug:

#240 FE-82 :wrench: 피드페이지 오류 수정
  src/pageLayout/Feed/EpigramFeed.tsx
Labels: Priority: High 🔥, Type: Merge :truck:, Type: Refactor :recycle:

#241 FE-82 :twisted_rightwards_arrows: 피드 페이지 목록 중복 오류 수정
  src/pageLayout/Feed/EpigramFeed.tsx
Labels: Priority: High 🔥, Type: Merge :truck:, Type: Refactor :recycle:

#242 FE-27 :twisted_rightwards_arrows: 브랜치 최신화
  package-lock.json
  src/components/main/RecentComment.tsx
  src/components/main/RecentEpigram.tsx
  src/pageLayout/Feed/EpigramFeed.tsx
Labels: Priority: High 🔥, Type: Merge :truck:

#244 FE-27 :ambulance: 마이페이지 누락 수정
  src/pages/mypage/index.tsx
Labels: Priority: High 🔥
